# Generated by Django 6.0 on 2025-12-22 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='about_image',
            field=models.ImageField(blank=True, null=True, upload_to='about/'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='about_paragraph_2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='core_values',
            field=models.TextField(default='We have a culture that is modern, relevant, and inspires students to have a brighter future. We are determined in our approach to learning, are creative in our thinking, and bold in our ambitions.'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='courses_count',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='lecturers_count',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='mission_statement',
            field=models.TextField(default='Our Mission is to promote excellence in the mining industry through professional development, knowledge sharing, and ethical practices, while contributing to sustainable development and socioeconomic growth in Ghana,'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='students_count',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='vision_statement',
            field=models.TextField(default='Our Mission is to promote excellence in the mining industry through professional development, knowledge sharing, and ethical practices, while contributing to sustainable development and socioeconomic growth in Ghana,'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='about_title',
            field=models.CharField(default='Know more about AfIMMP-TVET', max_length=200),
        ),
    ]
