# Generated by Django 6.0 on 2025-12-22 02:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefix', models.CharField(choices=[('Mr', 'Mr'), ('Mrs', 'Mrs'), ('Ms', 'Ms'), ('Dr', 'Dr'), ('Prof', 'Prof'), ('Engr', 'Engr')], max_length=10)),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10)),
                ('nationality', models.CharField(max_length=100)),
                ('home_address', models.TextField()),
                ('address_line_2', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(max_length=100)),
                ('state_region', models.CharField(max_length=100)),
                ('postal_code', models.CharField(max_length=20)),
                ('phone_number', models.CharField(max_length=15)),
                ('email_address', models.EmailField(max_length=254)),
                ('highest_education', models.CharField(choices=[('Primary', 'Primary'), ('JHS', 'JHS (Junior High School)'), ('SHS', 'SHS (Senior High School)'), ('Diploma', 'Diploma'), ('Certificate', 'Certificate'), ('Associate', 'Associate Degree'), ('Bachelor', "Bachelor's Degree"), ('Master', "Master's Degree"), ('PhD', 'PhD'), ('Other', 'Other')], max_length=50)),
                ('qualifications_certificates', models.TextField(help_text='List your qualifications/certificates')),
                ('institutions_attended', models.TextField(help_text="List institutions you've attended")),
                ('current_occupation', models.CharField(blank=True, max_length=200, null=True)),
                ('years_of_experience', models.IntegerField(blank=True, null=True)),
                ('relevant_skills', models.TextField(blank=True, null=True)),
                ('passport_photo', models.FileField(help_text='JPEG/PNG, max 5MB', upload_to='documents/passport_photos/')),
                ('birth_certificate_or_id', models.FileField(help_text='PDF/JPEG/PNG, max 10MB', upload_to='documents/birth_certificates/')),
                ('education_certificates', models.FileField(help_text='PDF/JPEG/PNG, max 10MB each, multiple files allowed', upload_to='documents/education_certificates/')),
                ('terms_conditions_accepted', models.BooleanField()),
                ('registration_fee_paid', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('enrollment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='registration', to='courses.enrollment')),
            ],
            options={
                'verbose_name': 'Course Registration',
                'verbose_name_plural': 'Course Registrations',
            },
        ),
    ]
