# Generated by Django 6.0 on 2026-04-02 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_courseregistration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='courses/'),
        ),
    ]
